<?php
/**
 * Created by PhpStorm.
 * User: Denis Khodakovskiy
 * Date: 18.11.2018
 * Time: 11:48
 */

namespace app\components\pi;

use app\components\esi\EVE;
use app\components\esi\universe\Type;

class Material
{
    const RAW_MATERIAL_AQUEOUS_LIQUIDS = 2268;
    const RAW_MATERIAL_BASE_METALS = 2267;
    const RAW_MATERIAL_CARBON_COMPOUNDS = 2288;
    const RAW_MATERIAL_MICROORGANISMS = 2073;
    const RAW_MATERIAL_NOBLE_METALS = 2270;
    const RAW_MATERIAL_IONIC_SOLUTIONS = 2309;
    const RAW_MATERIAL_NOBLE_GAS = 2310;
    const RAW_MATERIAL_REACTIVE_GAS = 2311;
    const RAW_MATERIAL_FELSIC_MAGMA = 2307;
    const RAW_MATERIAL_HEAVY_METALS = 2272;
    const RAW_MATERIAL_NON_CS_CRYSTALS = 2306;
    const RAW_MATERIAL_SUSPENDED_PLASMA = 2308;
    const RAW_MATERIAL_PLANKTIC_COLONIES = 2286;
    const RAW_MATERIAL_COMPLEX_ORGANISMS = 2287;
    const RAW_MATERIAL_AUTOTROPHS = 2305;

    const MATERIAL_BACTERIA = 2393;
    const MATERIAL_BIOFUELS = 2396;
    const MATERIAL_BIOMASS = 3779;
    const MATERIAL_CHIRAL_STRUCTURES = 2401;
    const MATERIAL_ELECTROLYTES = 2390;
    const MATERIAL_INDUSTRIAL_FIBERS = 2397;
    const MATERIAL_OXIDIZING_COMPOUND = 2392;
    const MATERIAL_OXYGEN = 3683;
    const MATERIAL_PLASMOIDS = 2389;
    const MATERIAL_PRECIOUS_METALS = 2399;
    const MATERIAL_PROTEINS = 2395;
    const MATERIAL_REACTIVE_METALS = 2398;
    const MATERIAL_SILICON = 9828;
    const MATERIAL_TOXIC_METALS = 2400;
    const MATERIAL_WATER = 3645;

    const TIER1_BIOCELLS = 2329;
    const TIER1_CONSTRUCTION_BLOCKS = 3828;
    const TIER1_CONSUMER_ELECTRONICS = 9836;
    const TIER1_COOLANT = 9832;
    const TIER1_ENRICHED_URANIUM = 44;
    const TIER1_FERTILIZER = 3693;
    const TIER1_GENETICALLY_ENHANCED_LIVESTOCK = 15317;
    const TIER1_LIVESTOCK = 3725;
    const TIER1_MECHANICAL_PARTS = 3689;
    const TIER1_MICROFIBER_SHIELDING = 2327;
    const TIER1_MINIATURE_ELECTRONICS = 9842;
    const TIER1_NANITES = 2463;
    const TIER1_OXIDES = 2317;
    const TIER1_POLYARAMIDS = 2321;
    const TIER1_POLYTEXTILES = 3695;
    const TIER1_ROCKET_FUEL = 9830;
    const TIER1_SILICATE_GLASS = 3697;
    const TIER1_SUPERCONDUCTORS = 9838;
    const TIER1_SUPERTENSILE_PLASTICS = 2312;
    const TIER1_SYNTHETIC_OIL = 3691;
    const TIER1_TEST_CULTURES = 2319;
    const TIER1_TRANSMITTER = 9840;
    const TIER1_VIRAL_AGENT = 3775;
    const TIER1_WATER_COOLED_CPU = 2328;

    const TIER2_BIOTECH_RESEARCH_REPORTS = 2358;
    const TIER2_CAMERA_DRONES = 2345;
    const TIER2_CONDENSATES = 2344;
    const TIER2_CRYOPROTECTANT_SOLUTION = 2367;
    const TIER2_DATA_CHIPS = 17392;
    const TIER2_GEL_MATRIX_BIOPASTE = 2348;
    const TIER2_GUIDANCE_SYSTEMS = 9834;
    const TIER2_HAZMAT_DETECTION_SYSTEMS = 2366;
    const TIER2_HERMETIC_MEMBRANES = 2361;
    const TIER2_HIGH_TECH_TRANSMITTERS = 17898;
    const TIER2_INDUSTRIAL_EXPLOSIVES = 2360;
    const TIER2_NEOCOMS = 2354;
    const TIER2_NUCLEAR_REACTORS = 2352;
    const TIER2_PLANETARY_VEHICLES = 9846;
    const TIER2_ROBOTICS = 9848;
    const TIER2_SMARTFAB_UNITS = 2351;
    const TIER2_SUPERCOMPUTERS = 2349;
    const TIER2_SYNTHETIC_SYNAPSES = 2346;
    const TIER2_TRANSCRANIAL_MICROCONTROLLERS = 12836;
    const TIER2_UKOMI_SUPERCONDUCTORS = 17136;
    const TIER2_VACCINES = 28974;

    const TIER3_BROADCAST_NODE = 2867;
    const TIER3_INTEGRITY_RESPONSE_DRONES = 2868;
    const TIER3_NANO_FACTORY = 2869;
    const TIER3_ORGANIC_MORTAR_APPLICATORS = 2870;
    const TIER3_RECURSIVE_COMPUTING_MODULE = 2871;
    const TIER3_SELF_HARMONIZING_POWER_CORE = 2872;
    const TIER3_STERILE_CONDUITS = 2875;
    const TIER3_WETWARE_MAINFRAME = 2876;

    /**
     * @param $material
     * @return Type|mixed|null
     */
    public static function type($material)
    {
        if (is_int($material)) {
            return EVE::universe()->type($material);
        }

        $types = EVE::universe()->ids([$material])->inventoryTypes;
        if (!$types) {
            return null;
        }

        $type = reset($types);

        return $type;
    }
}